### PR TITLE
Error handling: invalid ticker for portfolio (portfolio.py)

### PR DESCRIPTION
**Pull request by contactlp**
This pull request does two things.
1. If price is empty string it tries to get the today's price. Currently it tries to upload '' as price
2. If price is emptry and it try to ticker's today price and if ticker is not available in finviz, it does not add to portfolio (other wise portfolio creation fails)

### CODE REVIEW

**Comment by contactlp** [comment]
I have kept print statment, I think user want to know if some tickers are not being uploaded. I did not see you were any logging module,so I stick with print.

**Comment by mariostoev** [comment]
The logic is valid and good, since I didn't know that if you enter an invalid ticker it raises an IndexError. However, I believe that there shouldn't be any print statements in the library and instead, the program should raise a **custom** error. In this case you have to create a custom error class inside `error_handling.py` and raise it from there. You can do it like that:

```
class InvalidTicker: # for example
        def __init__(self, ticker):
                super(InvalidTicker, self).__init__(f'Invalid ticker {ticker} for portfolio') # for example
```

**Comment by contactlp** [comment]
@mariostoev added custom error handling.

**Comment by mariostoev** [comment]
Thank you @contactlp!

**Pull request merged**
